language: generic
services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_af80841cccbb_key -iv $encrypted_af80841cccbb_iv
  -in deploy.enc -out deploy -d
- docker build -t anastasiya108/art .
script:
- docker run -p 80:80 anastasiya108/art
addons:
  sshknownhosts:
  - 161.35.112.238
branches:
  only:
  - master


env:
  global:
  - REMOTEAPPDIR=/var/www/anastasiyaandrushchak.ca/
  - REMOTEUSER=deploy
  - REMOTEHOST=161.35.112.238
  - PORT=8080